### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [tchlux/util#1]
I suggest adding the topics `machine-learning`, `data-science`, `numerical-optimization`, `statistics`, `nonparametric` in the About section.

**Comment by tchlux** [comment]
Are you suggesting I edit the block that already exists and says

<img width="301" alt="image" src="https://user-images.githubusercontent.com/7769932/151001703-ac5fb973-30a7-485d-9331-89b813d990a1.png">

to instead just list the topics you said? Or is there a special place for me to assign "topics" to a repository?

**Comment by Beliavsky** [comment]
It should look like the About section of https://github.com/NaoMatch/FortLearner . How to add topics is explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .
